Repository redhat-cop/org, pull requests merged in 2020-06, with the labels that each got.

#193 Create gitlab-cleanup Quay repository
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#197 Added new contributors to CoP
  config.yaml
Labels: approved, lgtm, size/XS

#189 Add new team for declarative-openshift repo
  config.yaml
Labels: approved, lgtm, size/S

#198 Quay Workflow Management
  .github/workflows/quay-mgmt.yml
  ansible/playbooks/quay_management.yml
  ansible/requirements.yml
Labels: approved, lgtm, size/M

#202 Added quay repositories or AlertManager
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#201 New team for sqlserver COI
  config.yaml
Labels: approved, lgtm, size/S

#205 Add arthomasredhat as new contributor to CoP
  config.yaml
Labels: approved, lgtm, size/XS

#207 Adding prune-ocp-projects repo to quay.io
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/XS

#209 Add tom-stockwell as new contributor to container-cop
  config.yaml
Labels: approved, lgtm, size/XS

#213 Added garethahealy to github-actions
  config.yaml
Labels: approved, lgtm, size/XS

#212 Permissions for new bats-library repo
  config.yaml
Labels: approved, lgtm, size/S
