Repository redhat-cop/org, pull requests merged in 2020-07, with the labels that each got.

#216 Added apitanga to CoP
  config.yaml
Labels: approved, lgtm, size/XS

#222 Added CoP members
  config.yaml
Labels: approved, lgtm, size/XS

#223 Automation CoP Team permissions
  config.yaml
Labels: approved, lgtm, size/XS

#225 Adding new maintainer to BusinessAutomation cop
  config.yaml
Labels: approved, lgtm, size/XS

#227 Onboard jonahkh to MDT team
  config.yaml
Labels: approved, lgtm, size/XS

#229 New quay repository global-load-balancer-operator
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/XS

#234 ArgoCD robot account and repository for the operator
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#233 Add new contributors to CoP
  config.yaml
Labels: approved, lgtm, size/XS

#235 Add new CoP Managers to businessautomation cop team
  config.yaml
Labels: approved, lgtm, size/XS

#236 🐬 ADD - new maintainers and members for policies and bats 🐬
  config.yaml
Labels: approved, lgtm

#238 Add entry for the resource dispatcher to the group vars
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/XS
