Repository redhat-cop/org, pull requests merged in 2020-05, with the labels that each got.

#168 Added 9strands as CoP member
  config.yaml
Labels: approved, lgtm, size/XS

#169 Added Quay management of CoP org
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/L

#171 Additional members to ninja-program-admins team
  config.yaml
Labels: approved, lgtm, size/XS

#173 Add rego-policies repository
  config.yaml
Labels: approved, lgtm, size/S

#174 Added container security team
  config.yaml
Labels: approved, lgtm, size/S

#178 Added aizuddin85 to CoP
  config.yaml
Labels: approved, lgtm, size/XS

#177 Added repository to operators team
  config.yaml
Labels: approved, lgtm, size/XS

#179 New CoP quay repositories
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#185 Added bszeti, ckavili & lpsantil as CoP members
  config.yaml
Labels: approved, lgtm, size/XS

#180 Sync image repositories from Quay.io
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/M

#187 Added declarative-openshift repository permissions
  config.yaml
Labels: approved, lgtm, size/XS
