Repository redhat-cop/org, pull requests merged in 2020-01, with the labels that each got.

#86 Added CoP Bot account to admin
  OWNERS
  config.yaml
Labels: approved, lgtm, size/S

#88 Removed OpenShift CI robot accounts
  config.yaml
Labels: approved, lgtm, size/XS

#90 Add poolboy repository
  config.yaml
Labels: approved, lgtm, size/XS

#93 Add @pabrahamsson to admins group
  config.yaml
Labels: approved, lgtm, size/XS

#95 Add permissions for babylon-events-console
  config.yaml
Labels: approved, lgtm, size/XS

#97 Added robbbbh as CoP member
  config.yaml
Labels: approved, lgtm

#100 Add aglenn360 to CoP members
  config.yaml
Labels: approved, lgtm, size/XS

#102 Add richardwalkerdev to CoP members, fixes #101
  config.yaml
Labels: approved, lgtm, size/XS

#104 Migrate template2helm, fixes #103
  config.yaml
Labels: approved, lgtm, size/XS

#106 Added welshstew to CoP org members
  config.yaml
Labels: approved, lgtm, size/XS
