Repository redhat-cop/org, pull requests merged in 2020-02, with the labels that each got.

#111 Add cpitman to container-cop developers teams
  config.yaml
Labels: approved, lgtm, size/XS

#109 Added seravat to CoP org members
  config.yaml
Labels: approved, lgtm, size/XS

#112 Added pamenon to CoP org members
  config.yaml
Labels: approved, lgtm, size/XS

#114 Added jlozadad as Automation CoP mgr
  config.yaml
Labels: access, approved, lgtm, size/XS

#116 Added salar-nabb to CoP org members
  config.yaml
Labels: access, approved, lgtm, size/XS

#122 Add new team and repo for project-initialize-operator
  config.yaml
Labels: access, approved, lgtm, size/S

#118 Add businessautomation-cop team and repo config
  config.yaml
Labels: approved, lgtm, size/S

#123 Fix typos from PR 118
  config.yaml
Labels: approved, bug, lgtm, size/XS

#125 Added vdrvergara to CoP org members
  config.yaml
Labels: access, approved, lgtm, size/XS

#127 Added sushilsuresh to CoP org members
  config.yaml
Labels: approved, lgtm, size/XS

#129 Added linuxstudio to CoP member
  config.yaml
Labels: approved, lgtm, size/XS
