Repository redhat-cop/org, pull requests merged in 2020-03, with the labels that each got.

#131 Added danhawker to CoP org
  config.yaml
Labels: approved, lgtm, size/XS

#134 Fixing s/darktower/dark-tower permissions
  config.yaml
Labels: approved, lgtm, size/XS

#136 Added darthlukan to CoP org
  config.yaml
Labels: approved, lgtm, size/XS

#137 Added trv-rpeoples to CoP
  config.yaml
Labels: approved, lgtm, size/XS

#139 Add themoosman to MDT members
  config.yaml
Labels: approved, lgtm, size/XS

#142 Adding admins and mergers for the new github-actions repo
  config.yaml
Labels: approved, lgtm, size/S

#143 CASL org clean-up
  config.yaml
Labels: approved, lgtm, size/L

#144 Fixing incorrect permissions for infra-ansible
  config.yaml
Labels: approved, lgtm, size/XS

#145 Additional Quay members
  config.yaml
Labels: approved, lgtm, size/XS

#147 Added ddeno to CoP org
  config.yaml
Labels: approved, lgtm, size/XS

#150 Added nstrug to CoP team
  config.yaml
Labels: approved, lgtm, size/XS
