Repository redhat-cop/org, pull requests merged in 2021-06, with the labels that each got.

#373 Update gpte team members
  config.yaml
Labels: approved, lgtm, size/M

#374 Modifications for disconnected operators
  config.yaml
Labels: approved, lgtm, size/XS

#375 Add Evis Barbullushi (evisb) to GPTE
  config.yaml
Labels: approved, lgtm, size/XS

#377 Adding quay repo for anarchy-operator
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/XS

#378 Adding quay repos for babylon-catalog-api and babylon-catalog-ui
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#380 Adding jfilipcz to CoP + creating quay.io repo for new monitoring image
  ansible/inventory/group_vars/all.yml
  config.yaml
Labels: approved, lgtm, size/S
