Repository redhat-cop/org, pull requests merged in 2021-08, with the labels that each got.

#391 Permissions for community-operators-prod repository
  config.yaml
Labels: size/XS, approved, lgtm

#393 GitOps Teams and Maintainers
  config.yaml
Labels: size/S, approved, lgtm

#395 Updated CoP owners
  config.yaml
Labels: size/XS, approved, lgtm

#396 Add distributed working cop
  config.yaml
Labels: size/S, approved, lgtm

#397 Add Gareth Healy to OWNERS file
  OWNERS
Labels: size/XS, approved, lgtm

#399 Config cleanup
  config.yaml
Labels: approved, lgtm, size/L

#401 Add 9strands to gpte team
  config.yaml
Labels: size/XS, approved, lgtm

#402 Add vaibhavjainwiz as a CoP member
  config.yaml
Labels: size/XS, approved, lgtm
