Repository redhat-cop/org, pull requests merged in 2021-03, with the labels that each got.

#333 Added ocp-disconnected team/members
  config.yaml
Labels: approved, lgtm, size/S

#335 Renamed volume-expander-operator-bundle Quay repository
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/XS

#336 Added itewk to CoP
  config.yaml
Labels: approved, lgtm, size/XS

#338 Add chadhellyea as CoP member
  config.yaml
Labels: approved, lgtm, size/XS

#342 Add day0hero & tosmi as CoP members
  config.yaml
Labels: approved, lgtm, size/XS

#345 Add rflorenc & berkeragir as CoP members
  config.yaml
Labels: approved, lgtm, size/XS

#349 Added CoP members
  config.yaml
Labels: approved, lgtm, size/XS

#351 Add johnsimcall as CoP member
  config.yaml
Labels: approved, lgtm, size/XS

#359 Renaming 'master' to 'main'
  .github/workflows/quay-mgmt.yml
Labels: approved, lgtm, size/XS

#356 Adding quay.io/babylon-admin & babylon team
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/M

#354 golang CoP
  config.yaml
Labels: approved, lgtm, size/S

#360 Added poolboy-admin Quay repository
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/S

#361 Add andeahall12 and jscar-hawk as CoP members
  config.yaml
Labels: approved, lgtm, size/XS

#362 Add initial repo definitions for new prometheus exporters & team for them
  ansible/inventory/group_vars/all.yml
Labels: approved, lgtm, size/M
