Repository redhat-cop/org, pull requests merged in 2022-02, with the labels that each got.

#451 Add mophahr and tech2734 as automation CoP managers
  config.yaml
Labels: size/S, approved, lgtm

#458 Fix username typo, fixes #457
  config.yaml
Labels: size/XS, approved, lgtm

#463 Add Trevor Box to operators-wg-mergers
  config.yaml
Labels: access, size/XS, approved, lgtm

#465 Added trevorbox to CoP members
  config.yaml
Labels: size/XS, approved, lgtm

#467 Permissions for vault-plugin-secrets-quay
  config.yaml
Labels: size/XS, approved, lgtm
